# Generated by Django 4.2.7 on 2024-05-11 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_consult'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='consult',
            table='consult',
        ),
    ]
