# Generated by Django 4.2.7 on 2024-05-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_consult_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult',
            name='phone',
            field=models.IntegerField(default=123, max_length=15, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
