# Generated by Django 4.2.7 on 2024-05-11 13:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_consult_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult',
            name='phone',
            field=models.BigIntegerField(default=123, validators=[django.core.validators.MinValueValidator(999999)], verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
