# Generated by Django 4.2.7 on 2024-05-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_consult_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult',
            name='phone',
            field=models.CharField(default=123, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
