# Generated by Django 4.2.7 on 2024-04-22 15:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_categories_options_alter_categories_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='color',
            field=models.CharField(choices=[('black', 'Черный'), ('white', 'Белый'), ('grey', 'Серый'), ('red', 'Красный'), ('blue', 'Синий'), ('yellow', 'Желтый'), ('green', 'Зеленый'), ('brown', 'Коричневый')], default=1, max_length=15, verbose_name='Цвет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='engine',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0.6), django.core.validators.MaxValueValidator(15.0)], verbose_name='Объем двигателя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='fuel',
            field=models.CharField(choices=[('gasoline', 'Бензин'), ('diesel', 'Дизель'), ('electric', 'Электро')], default=1, max_length=15, verbose_name='Топливо'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='gearbox',
            field=models.CharField(choices=[('manual', 'Механическая'), ('automatic', 'Автомат'), ('robotic', 'Робот'), ('variator', 'Вариатор')], default=1, max_length=15, verbose_name='Коробка передач'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='cars_images', verbose_name='Изображение2'),
        ),
        migrations.AddField(
            model_name='products',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='cars_images', verbose_name='Изображение3'),
        ),
        migrations.AddField(
            model_name='products',
            name='mileage',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10000000)], verbose_name='Пробег'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='power',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5000)], verbose_name='Мощность'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='year',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)], verbose_name='Год'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Скидка в %'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cars_images', verbose_name='Изображение1'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Модель'),
        ),
    ]
