# Generated by Django 4.2.7 on 2024-04-22 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_products_color_products_engine_products_fuel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Скидка в %'),
        ),
        migrations.AlterField(
            model_name='products',
            name='engine',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(15.0)], verbose_name='Объем двигателя'),
        ),
    ]
