# Generated by Django 4.2.7 on 2024-04-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_products_discount_alter_products_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='color',
            field=models.CharField(choices=[('Черный', 'Черный'), ('Белый', 'Белый'), ('Серый', 'Серый'), ('Красный', 'Красный'), ('Синий', 'Синий'), ('Желтый', 'Желтый'), ('Зеленый', 'Зеленый'), ('Коричневый', 'Коричневый')], max_length=15, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='products',
            name='fuel',
            field=models.CharField(choices=[('Бензин', 'Бензин'), ('Дизель', 'Дизель'), ('Электро', 'Электро')], max_length=15, verbose_name='Топливо'),
        ),
        migrations.AlterField(
            model_name='products',
            name='gearbox',
            field=models.CharField(choices=[('Механическая', 'Механическая'), ('Автомат', 'Автомат'), ('Робот', 'Робот'), ('Вариатор', 'Вариатор')], max_length=15, verbose_name='Коробка передач'),
        ),
    ]
