# Generated by Django 4.2.7 on 2024-05-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_products_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, max_length=550, null=True, verbose_name='Описание'),
        ),
    ]
