# Generated by Django 4.2.7 on 2024-05-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='installment',
            field=models.BooleanField(blank=True, null=True, verbose_name='Вариант кредита'),
        ),
    ]
