# Generated by Django 4.2.7 on 2024-05-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=9999999999, max_length=20, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
