# Generated by Django 4.2.7 on 2024-05-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='installment',
            field=models.BooleanField(default=0, verbose_name='Вариант кредита'),
        ),
    ]
