# Generated by Django 4.2.7 on 2024-05-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_installment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default=123, max_length=100, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default=123, max_length=100, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='installment',
            field=models.IntegerField(choices=[(0, 'Нет'), (1, '24 месяца'), (2, '36 месяцев'), (3, '60 месяцев')], default=0, verbose_name='Вариант кредита'),
        ),
    ]
