# Generated by Django 4.2.7 on 2024-05-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_payment_on_get_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(verbose_name='Оплачено'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_on_get',
            field=models.BooleanField(verbose_name='Оплата при получении'),
        ),
        migrations.AlterField(
            model_name='order',
            name='requires_installment',
            field=models.BooleanField(verbose_name='Требуется кредит'),
        ),
    ]
