# Generated by Django 4.2.7 on 2024-05-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='requires_delivery',
            field=models.BooleanField(verbose_name='Требуется доставка'),
        ),
    ]
