# Generated by Django 4.2.7 on 2024-05-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_requires_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='requires_delivery',
            field=models.BooleanField(choices=[(0, False), (1, True)], default=False, verbose_name='Требуется доставка'),
        ),
    ]
