# Generated by Django 4.2.7 on 2024-05-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_order_requires_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='requires_delivery',
            field=models.BooleanField(choices=[(0, 'False'), (1, 'True')], default=1, verbose_name='Требуется доставка'),
        ),
    ]
