# Generated by Django 4.2.7 on 2024-05-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_order_requires_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='requires_delivery',
            field=models.IntegerField(choices=[(0, 'Нет'), (1, 'Да')], default=0, verbose_name='Требуется доставка'),
        ),
    ]
