# Generated by Django 4.2.7 on 2024-05-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_order_payment_on_get_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='installment',
            field=models.IntegerField(choices=[(0, 'Не выбран'), (1, '24 месяца'), (2, '36 месяцев'), (3, '60 месяцев')], default=0, verbose_name='Вариант кредита'),
        ),
    ]
