# Generated by Django 4.2.7 on 2024-05-09 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
