# Generated by Django 4.2.7 on 2024-05-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='monthly_payment',
            field=models.IntegerField(default=0, verbose_name='Ежемесячный платеж'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Общая стоимость заказа'),
        ),
    ]
