# Generated by Django 4.2.7 on 2024-05-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_order_monthly_payment_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Проданный автомобиль', 'verbose_name_plural': 'Проданных автомобилей'},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='category',
            field=models.CharField(default=1, max_length=150, verbose_name='Марка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Модель'),
        ),
    ]
