# Generated by Django 4.2.7 on 2024-05-09 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_alter_orderitem_options_orderitem_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Проданный автомобиль', 'verbose_name_plural': 'Проданные автомобили'},
        ),
    ]
