# Generated by Django 4.2.7 on 2024-05-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_alter_orderitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Общая стоимость заказа'),
        ),
    ]
