# Generated by Django 4.2.7 on 2024-05-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_remove_orderitem_name_alter_orderitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_on_get',
            field=models.IntegerField(choices=[(0, 'Нет'), (1, 'Да')], verbose_name='Оплата при получении'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Нет'), (1, 'Да')], default=0, verbose_name='Статус заказа'),
        ),
    ]
