# Generated by Django 4.2.7 on 2024-05-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'В обработке'), ('waiting_payment', 'Ожидает оплаты'), ('ready', 'Готов к выдаче'), ('shipping', 'В доставке'), ('completed', 'Завершен')], default=0, verbose_name='Статус заказа'),
        ),
    ]
